### ISSUE TITLE
Everything black

### ISSUE THREAD

**Issue by ArenaMMORPG** [root-BB/witcher3map#8]
Hello, how to fix this?

![image](https://github.com/root-BB/witcher3map/assets/38107216/2ae33739-7001-4c41-8477-b0b75fa56b2c)

**Comment by ArenaMMORPG** [comment]
I get this message and then map breaks somehow
![image](https://github.com/root-BB/witcher3map/assets/38107216/65b6cf38-8a7b-4ba1-9c79-f66613b11daa)

**Comment by msinger** [comment]
It is all black for me too if I try to open it locally. I don't know why. Someone is hosting it here: https://www.tivaprojects.com/witcher3map/
There it works.

**Comment by root-BB** [comment]
This problem is not caused by a software error. It is caused by Windows' security configuration. If you want to run the map locally, you can use one of the offline maps with different methods via the [Nexus page](https://www.nexusmods.com/witcher3/mods/6061). If you want to use it online, you can use the [online map](https://root-bb.github.io/witcher3map/).
